# Generated by Django 2.2.24 on 2022-12-29 18:28

from django.db import migrations
import phonenumbers


def normalize_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats.iterator():
        number = flat.owners_phonenumber
        parsed_number = phonenumbers.parse(number, "RU")
        if phonenumbers.is_possible_number(parsed_number) and \
                phonenumbers.is_valid_number(parsed_number):
            normalized_number = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.INTERNATIONAL,
            )
            flat.owner_pure_phone = normalized_number
        else:
            flat.owner_pure_phone = ""
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221229_2114'),
    ]

    operations = [
        migrations.RunPython(normalize_numbers),
    ]
