# Generated by Django 2.2.24 on 2022-12-30 21:39

from django.db import migrations


def set_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        flats = Flat.objects.filter(
            owner=owner.owner,
            owners_phonenumber=owner.owners_phonenumber,
        )
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221231_0037'),
    ]

    operations = [
        migrations.RunPython(set_flats),
    ]
