# Generated by Django 2.2.24 on 2022-12-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20221231_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='flats',
            new_name='owned_flats',
        ),
    ]
