# Generated by Django 2.2.24 on 2022-12-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20221231_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owned_flats',
            field=models.ManyToManyField(db_index=True, related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
