# Generated by Django 2.2.24 on 2023-01-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20221231_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_flats',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
